{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki.yaml: |
    {{- toYaml .Values.config.data | nindent 4 }}
{{- end }}