apiVersion: v2
name: mcp-sdcpp
description: Vibe coded MCP (Model Context Protocol) adapter for the native stable-diffusion.cpp sdcpp API. Provides a bridge between MCP-compatible clients and the sdcpp API for image generation and editing.

type: application
version: 0.1.3
appVersion: "0.1.0"

maintainers:
  - name: Damien FLETY
    email: damfle+github@proton.me

keywords:
  - mcp-sdcpp
  - gateway
  - sdcpp

home: https://github.com/damfle/helm-charts
sources:
  - https://github.com/damfle/helm-charts
  - https://git.flety.net/damien/mcp-sdcpp

dependencies:
  - name: generic
    version: "1.0.10"
    repository: "https://damfle.github.io/helm-charts"
