# Configuration for chart-testing
# See: https://github.com/helm/chart-testing#configuration

# Directories containing charts
chart-dirs:
  - .

# Chart repositories to add before running tests
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - prometheus-community=https://prometheus-community.github.io/helm-charts

# Lint configuration
lint-conf: .github/linters/lintconf.yaml

# Helm extra arguments
helm-extra-args: --timeout=600s

# Check version increment
check-version-increment: true

# Validate maintainers in Chart.yaml
validate-maintainers: false

# Validate chart version is present in CHANGELOG.md
validate-chart-schema: true

# Additional yamllint config
additional-commands:
  - helm unittest

# Target branch for comparison
target-branch: main

# Charts to exclude from testing
excluded-charts: []

# Upgrade tests
upgrade: false
