apiVersion: v2
name: ngircd
description: A Helm chart for ngIRCd - A self-hosted IRC server.
type: application
version: 0.1.8
appVersion: "latest"
home: https://ngircd.barton.de/
sources:
  - https://github.com/ngircd/ngircd
keywords:
  - ngircd
  - irc
  - cpp

maintainers:
  - name: damfle
    email: damfle+github@proton.me
dependencies:
  - name: generic
    version: "1.0.10"
    repository: https://damfle.github.io/helm-charts
