apiVersion: v2
name: jupyter
description: A Helm chart for Jupyter Notebook/Lab server with GPU support

# A chart can be either an 'application' or a 'library' chart.
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "0.1.2"

maintainers:
  - name: Damien FLETY
    email: damfle+github@proton.me

keywords:
  - jupyter
  - notebook
  - lab
  - python
  - data-science
  - ml
  - gpu
  - nvidia

home: https://github.com/damfle/helm-charts
sources:
  - https://github.com/damfle/helm-charts
