apiVersion: v1
entries:
  generic:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-10-01T09:42:38.355717471Z"
    description: A Helm chart for Kubernetes
    digest: 616c08d1b276f96242a6a00e2f181cabc7a20c0297b55686429228d4fa519ad8
    name: generic
    type: application
    urls:
    - https://damfle.github.io/helm-charts/charts/generic-0.1.16.tgz
    version: 0.1.16
  loki:
  - apiVersion: v2
    appVersion: 2.9.0
    created: "2025-10-01T09:42:38.356866115Z"
    dependencies:
    - name: generic
      repository: file://../generic
      version: 0.1.15
    description: A Helm chart for Grafana Loki - Log aggregation system
    digest: d5a75868bbf270cbb77df6b646aad6f3902d5d4cce523cd20f8d59c67256a31c
    home: https://grafana.com/oss/loki/
    keywords:
    - loki
    - grafana
    - logging
    - observability
    - monitoring
    maintainers:
    - email: damien@example.com
      name: Damien
    name: loki
    sources:
    - https://github.com/grafana/loki
    type: application
    urls:
    - https://damfle.github.io/helm-charts/charts/loki-0.1.18.tgz
    version: 0.1.18
generated: "2025-10-01T09:42:38.35505827Z"
