apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pterodactyl.fullname" . }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
spec:
  replicas: {{ .Values.panel.replicaCount }}
  selector:
    matchLabels:
      {{- include "pterodactyl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.panel.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pterodactyl.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: panel
        {{- with .Values.panel.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.panel.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.panel.image.repository }}:{{ .Values.panel.image.tag }}"
          imagePullPolicy: {{ .Values.panel.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.panel.service.port }}
              protocol: TCP
          env:
            - name: APP_TIMEZONE
              value: {{ .Values.pterodactyl.app.timezone | quote }}
            - name: APP_SERVICE_AUTHOR
              value: {{ .Values.pterodactyl.app.adminEmail | quote }}
            - name: APP_URL
              value: {{ .Values.pterodactyl.app.url | quote }}
            - name: APP_ENV
              value: {{ .Values.pterodactyl.app.env | quote }}
            - name: APP_ENVIRONMENT_ONLY
              value: {{ .Values.pterodactyl.app.envOnly | quote }}
            - name: HASHIDS_LENGTH
              value: "8"
            - name: DB_DRIVER
              value: "mariadb"
            - name: DB_HOST
              value: "{{ .Values.pterodactyl.database.host | default (printf "%s-mariadb" (include "pterodactyl.fullname" .)) }}"
            - name: DB_PORT
              value: "{{ .Values.pterodactyl.database.port }}"
            - name: DB_DATABASE
              value: "{{ .Values.pterodactyl.database.name }}"
            - name: DB_USERNAME
              value: "{{ .Values.pterodactyl.database.user }}"
            {{- if .Values.pterodactyl.database.password }}
            - name: DB_PASSWORD
              value: "{{ .Values.pterodactyl.database.password }}"
            {{- else }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pterodactyl.fullname" . }}-secrets
                  key: mariadb-password
                  optional: true
            {{- end }}


            - name: REDIS_HOST
              value: "{{ .Values.pterodactyl.redis.host | default (printf "%s-redis" (include "pterodactyl.fullname" .)) }}"
            - name: REDIS_PORT
              value: {{ .Values.pterodactyl.redis.port | quote }}

            {{- if .Values.pterodactyl.redis.password }}
            - name: REDIS_PASSWORD
              valueFrom: {{- toYaml .Values.pterodactyl.redis.password | nindent 16 }}
            {{- end }}
            - name: CACHE_DRIVER
              value: "redis"
            - name: SESSION_DRIVER
              value: "redis"
            - name: QUEUE_DRIVER
              value: "redis"

            {{- /* Mail configuration */}}
            - name: MAIL_FROM
              value: {{ .Values.pterodactyl.smtp.from | quote }}
            - name: MAIL_DRIVER
              value: "smtp"
            - name: MAIL_HOST
              value: {{ .Values.pterodactyl.smtp.host | quote }}
            - name: MAIL_PORT
              value: {{ .Values.pterodactyl.smtp.port | quote }}
            - name: MAIL_USERNAME
              value: {{ .Values.pterodactyl.smtp.username | quote }}
            - name: MAIL_PASSWORD
              value: {{ .Values.pterodactyl.smtp.password | quote }}
            - name: MAIL_ENCRYPTION
              value: {{ .Values.pterodactyl.smtp.ssl | quote }}

            {{- /* Additional user-defined environment variables */}}
            {{- with .Values.panel.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.panel.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.panel.livenessProbe.enabled }}
          {{- with (omit .Values.panel.livenessProbe "enabled") }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.panel.readinessProbe.enabled }}
          {{- with (omit .Values.panel.readinessProbe "enabled") }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.panel.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.panel.persistence.enabled }}
            - name: {{ include "pterodactyl.fullname" . }}-storage
              mountPath: {{ .Values.panel.persistence.mountPath | default "/data" }}
              {{- if .Values.panel.persistence.subPath }}
              subPath: {{ .Values.panel.persistence.subPath }}
              {{- end }}
            {{- end }}
            {{- with .Values.panel.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

      volumes:
        {{- if .Values.panel.persistence.enabled }}
        - name: {{ include "pterodactyl.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "pterodactyl.fullname" . }}
        {{- end }}
        {{- with .Values.panel.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.panel.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.panel.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.panel.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
