{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pterodactyl.fullname" . }}-mariadb
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pterodactyl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pterodactyl.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mariadb
    spec:
      {{- with .Values.mariadb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          {{- with .Values.mariadb.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mariadb.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          {{- with .Values.mariadb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mariadb.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          {{- if .Values.mariadb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pterodactyl.fullname" . }}-mariadb
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.mariadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
