{{- if .Values.panel.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pterodactyl.fullname" . }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
  {{- with .Values.panel.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.panel.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.panel.persistence.size | quote }}
  {{- if .Values.panel.persistence.storageClassName }}
  storageClassName: {{ .Values.panel.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
